Repository deeplearningunb/Sign-Language-Digits-Detector, pull requests merged in 2019-11, with the labels that each got.

#12 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, open source

#13 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, open source

#10 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, open source

#11 Create LICENSE
  LICENSE
Labels: documentation, open source

#15 Add dataset
  .gitignore
  .ipynb_checkpoints/SL-Digits-Detector-checkpoint.ipynb
  SL-Digits-Detector.ipynb
Labels: data processing, dataset

#19 Data augmentation
  .gitignore
  .ipynb_checkpoints/SL-Digits-Detector-checkpoint.ipynb
  SL-Digits-Detector.ipynb
Labels: data augmentation, enhancement

#25 Created README.MD
  README.md
Labels: documentation, open source
